name: sudoku_solver
description: A Sudoku game developed in Flutter AD micro Project.
publish_to: 'none'
version: 1.0.0


environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
